
attr_config                   = "config"
attr_masterfile               = "master.xlsx"
attr_setting_shtname          = "設定"
attr_skill_shtname            = "スキル表"
attr_route_assignment_shtname = "ルート割当表"
attr_route_shtname            = "ルート表"
attr_overworktime_shtname         = "残業予定"
attr_overworktime_raw_shtname     = "残業実績"
attr_holiday_shtname          = "作業員予定表"
attr_worked_route_raw_shtname = "作業ルート実績"
attr_worked_time_raw_shtname  = "作業時間実績"
attr_ingore_workers_shtname   = "シフト割り振り無効対象"
attr_customer_route_shtname   = "顧客ルート表"
attr_log_file                 = "log.txt"

inf = 100000000
eps = 1e-6

param_outputfile    = "出力ファイル"
param_targetmonth   = "開始日付"
param_nday          = "期間"
param_timelimit     = "計算時間"
param_publicholiday = "公休日"
param_skill_standard_val = "スキル表基準値"
param_department    = "処理対象部署"
param_diffstarttime = "開始時間許容差"

param_holiday_const_name =  "休日を2週に1度とする制約条件"
param_pulic_holiday_const_name = "公休日に関する制約条件"
param_worktime_year_const_name = "1年間の拘束時間に関する制約条件"
param_worktime_month_const_name = "1ヶ月の拘束時間に関する制約条件"
param_resttime_const_name = "1日の休息時間に関する制約条件"
param_dayave_const_name = "2日の1日平均に関する制約条件"
param_weekave_const_name = "2週の1週平均に関する制約条件"